from datetime import date

from pydantic import BaseModel, ConfigDict, Field


class SeshatVariable(BaseModel):
    section: str = Field(..., description="'Section' as the Equinox file gives it, 'Warfare variables'. Only the variables Equinox codes are kept — 145 of the codebook's 1 555 — each under the section and subsection where most of its rows sit, so the clerical strays (a Copper row with no subsection) do not make variables of their own.")
    subsection: str | None = Field(None, description="'Subsection' as the Equinox file gives it, 'Military Technologies'. Empty for the variables Equinox files directly under a section, such as RA or Capital.")
    name: str = Field(..., description="'Variable' as the Equinox file gives it, 'Polity territory'. With section and subsection it is the key: RA recurs once per section, Duration once for the polity and once per ritual. It is also the comment on the matching seshat_information column, which is how a column finds its definition.")
    definition: str | None = Field(None, description="The text the Legacy Codebook (Equinox) gives after ♥ for this variable, in its own wording: the allowed codes ('absent/present/unknown'), the unit ('in squared kilometers'), or a definition. Matched on the name, under the codebook heading that bears the subsection or section. Empty where the codebook lists the variable without one.")
    notes: str | None = Field(None, description="The codebook lines that follow the definition up to the next variable or heading, such as the meaning of each code of 'Degree of centralization'. Taken as they fall in the file, so an introduction to the next group of variables can land here.")


class SeshatValue(BaseModel):
    value_from: str | int | None = Field(None, description="'Value.From', the coded value as published: a presence code ('present', 'inferred absent', 'suspected unknown' — the codebook's coding conventions define each), a number, or a name. Numbers arrive as integers, everything else as text. When value_note is 'range' it is the lower bound.")
    value_to: str | int | None = Field(None, description="'Value.To', the upper bound of a range — Polity Population 50000 to 60000. Filled only when value_note is 'range', on 1 126 of 47 477 rows.")
    date_from: str | None = Field(None, description="'Date.From', with the era glued to the year: '115BCE', '1300CE'. Empty on 46 031 rows, where the value holds for the polity's whole span. Filled without date_to, it dates the value to that single year — how a changing Polity territory is published.")
    date_to: str | None = Field(None, description="'Date.To', same format. The codebook puts uncertainty on values, never on dates, so a date here is always exact.")
    fact_type: str | None = Field(None, description="'Fact.Type', 'simple' or 'complex'. A complex row is always one of several the coder's single entry was split into — the items of a list, or a value that changed over dated periods. Simple rows can share a variable too: that is how an uncertain or disputed value is published.")
    value_note: str | None = Field(None, description="'Value.Note': 'simple'; 'list', one item of a list; 'range', see value_to; 'uncertain', the codebook's [a; b] — one row per extreme, the coder cannot tell which held; 'disputed', the codebook's {a; b} — one row per expert opinion. An uncertain or disputed variable has more than one value and none of them is the answer.")
    date_note: str | None = Field(None, description="'Date.Note': 'range' when date_to is filled, empty otherwise.")


class Period(BaseModel):
    start_year: int | None = Field(None, description="First year. Negative before the common era.")
    end_year: int | None = Field(None, description="Last year.")


class CliopatriaLink(BaseModel):
    cliopatria_id: int | None = Field(None, description="Cultura's Polity.cliopatria_id, the key to CliopatriaPolity.")
    name: str | None = Field(None, description="The polity's name as Cliopatria spells it, 'Kingdom of France'.")
    periods: tuple[Period, ...] = Field((), description="The years over which Cliopatria gives this Seshat id to that polity, oldest first: its territories carrying the id, with consecutive ones merged. Several when the id comes and goes, as a relation between two polities can.")


class SeshatPolity(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    polity_long_name: str | None = Field(None, description="'polity_long_name', 'Abbasid Caliphate I'.")
    id: int | None = Field(None, description="'id', the polity's number on seshat-db.com — the n of seshat-db.com/core/polity/n. 864 polities, the whole of Seshat's list on 2026-09-29, not only the 373 Equinox codes.")
    url: str | None = Field(None, description="'url', the polity's page on seshat-db.com. The page is where the new and old ids stand side by side, 'af_durrani_emp / AfDurrn'; the API returns only the new one.")
    macro_region: str | None = Field(None, description="'macro_region', 'Southwest Asia'.")
    home_seshat_region: str | None = Field(None, description="'home_seshat_region', a region inside the macro region, 'Mesopotamia'.")
    polity_new_id: str | None = Field(None, description="'polity_new_ID', the id Seshat uses today, 'af_durrani_emp'. It is the form Cliopatria's SeshatID takes, so it is the join to PolityCliopatria.seshat_id: 540 of Cliopatria's 546 distinct ids are here. Cliopatria sometimes packs two in one field, 'de_empire_2;it_sicily_k_2', which must be split first.")
    polity_old_id: str | None = Field(None, description="'polity_old_ID', the id Equinox uses, 'AfDurrn', which SeshatInformation.seshat_polity carries. On 313 polities it simply repeats the new id — mostly those added after Equinox, which never had an old one, but also 36 tagged Equinox 2020.")
    start_year: int | None = Field(None, description="'start_year', negative before the common era.")
    end_year: int | None = Field(None, description="'end_year'.")
    home_nga: str | None = Field(None, description="'home_nga', the Natural Geographic Area the polity was sampled from. Filled on 376 of 864: only the polities of the NGA sample have one.")
    g: bool | None = Field(None, alias="g (General Variables)", description="'G', whether the polity has General Variables coded. This and the seven flags below are the section badges of Seshat's polity list; their meanings come from the tooltips there. Each flag is stored under its code and meaning, 'g (General Variables)', so a record reads without this model.")
    sc: bool | None = Field(None, alias="sc (Social Complexity Variables)", description="'SC', Social Complexity Variables.")
    wf: bool | None = Field(None, alias="wf (Warfare Variables)", description="'WF', Warfare Variables (MilTech).")
    rt: bool | None = Field(None, alias="rt (Religion Variables)", description="'RT', Religion Variables.")
    hs: bool | None = Field(None, alias="hs (Human Sacrifice)", description="'HS', Human Sacrifice. The site's tooltips do not name it; the meaning is inferred from the data: the 323 polities flagged are exactly those in Seshat's rt/human-sacrifices API.")
    cc: bool | None = Field(None, alias="cc (Crisis Consequences)", description="'CC', Crisis Consequences.")
    pt: bool | None = Field(None, alias="pt (Power Transition)", description="'PT', Power Transition.")
    in_: bool | None = Field(None, alias="in (Instability Events)", description="'IN', Instability Events. The field is in_ in Python because 'in' is a keyword; the stored key is the alias.")
    polity_tag: str | None = Field(None, description="'polity_tag', the batch the polity was added in: 'Equinox 2020 Polities' on 564, 'Other Polities' on 200, and 'NEW ... Polities' for regional additions.")
    shapefile_name: str | None = Field(None, description="'shapefile_name', the name of the polity's shape in Seshat's own maps, 'Aghlabid Dynasty'. Filled on 81.")
    link_to_cliopatria: tuple[CliopatriaLink, ...] = Field((), description="Not in Seshat's list: added by this project. The Cliopatria polities that carry this polity's polity_new_id as their SeshatID, and when — read off Cultura's polity table, whose territories already carry Cliopatria's SeshatID, the fields that pack two ids, 'de_empire_2;it_sicily_k_2', split. Usually one polity: fr_bourbon_k_2 is the Kingdom of France over 1662–1791. Empty for a polity Cliopatria does not link to.")


class SeshatInformation(BaseModel):
    seshat_polity: SeshatPolity = Field(..., description="The polity, as its entry in Seshat's polity list: the Equinox 'Polity' id is its polity_old_id, the Equinox 'NGA' its home_nga. It is the key: 373 polities, 46 to 167 coded rows each, and polity_new_id is the id Cliopatria's SeshatID uses. GbEmpr2, InGurjr and InKanau are missing from the list, so their entry holds only polity_old_id and home_nga, both taken from Equinox. Equinox's NGA is the one the polity was sampled in, which is not always its home: for IrSeleu it is Susiana, for JpNara* Kansai, and those two are lost. The raw file is long, one row per coded value; every field below gathers the rows of one 'Variable', and the file's 'Section' and 'Subsection' are dropped because the variable implies them. What each variable means is in SeshatVariable. The few rows filed elsewhere are clerical: 115 Warfare rows with no subsection, 14 ideology rows under a misspelled or wrong subsection.")
    ra: dict[str, tuple[str, ...]] = Field({}, description="'RA', the research assistants who coded the polity, keyed by the section they coded: {'Warfare variables': ('Enrico Cioni',)}. The file repeats RA once per section, so it is a map rather than a list.")
    ritual_duration: dict[str, tuple[SeshatValue, ...]] = Field({}, description="'Duration' as published under the ritual subsections — 'Most euphoric collective ritual of the official cult' — and filed under Warfare variables. It is the duration of the ritual in hours, not of the polity, so it cannot share the duration field. Six rows in the whole file.")
    original_name: tuple[SeshatValue, ...] = ()
    alternative_names: tuple[SeshatValue, ...] = ()
    peak_date: tuple[SeshatValue, ...] = ()
    duration: tuple[SeshatValue, ...] = ()
    degree_of_centralization: tuple[SeshatValue, ...] = ()
    supra_polity_relations: tuple[SeshatValue, ...] = ()
    preceding_quasi_polity: tuple[SeshatValue, ...] = ()
    relationship_to_preceding_quasi_polity: tuple[SeshatValue, ...] = ()
    succeeding_quasi_polity: tuple[SeshatValue, ...] = ()
    capital: tuple[SeshatValue, ...] = ()
    language: tuple[SeshatValue, ...] = ()
    supracultural_entity: tuple[SeshatValue, ...] = ()
    scale_of_supra_cultural_interaction: tuple[SeshatValue, ...] = ()
    polity_territory: tuple[SeshatValue, ...] = ()
    polity_population: tuple[SeshatValue, ...] = ()
    population_of_the_largest_settlement: tuple[SeshatValue, ...] = ()
    settlement_hierarchy: tuple[SeshatValue, ...] = ()
    administrative_levels: tuple[SeshatValue, ...] = ()
    religious_levels: tuple[SeshatValue, ...] = ()
    military_levels: tuple[SeshatValue, ...] = ()
    professional_military_officers: tuple[SeshatValue, ...] = ()
    professional_soldiers: tuple[SeshatValue, ...] = ()
    professional_priesthood: tuple[SeshatValue, ...] = ()
    full_time_bureaucrats: tuple[SeshatValue, ...] = ()
    examination_system: tuple[SeshatValue, ...] = ()
    merit_promotion: tuple[SeshatValue, ...] = ()
    specialized_government_buildings: tuple[SeshatValue, ...] = ()
    formal_legal_code: tuple[SeshatValue, ...] = ()
    judges: tuple[SeshatValue, ...] = ()
    courts: tuple[SeshatValue, ...] = ()
    professional_lawyers: tuple[SeshatValue, ...] = ()
    irrigation_systems: tuple[SeshatValue, ...] = ()
    drinking_water_supply_systems: tuple[SeshatValue, ...] = ()
    markets: tuple[SeshatValue, ...] = ()
    food_storage_sites: tuple[SeshatValue, ...] = ()
    roads: tuple[SeshatValue, ...] = ()
    bridges: tuple[SeshatValue, ...] = ()
    canals: tuple[SeshatValue, ...] = ()
    ports: tuple[SeshatValue, ...] = ()
    mines_or_quarries: tuple[SeshatValue, ...] = ()
    nonwritten_records: tuple[SeshatValue, ...] = ()
    written_records: tuple[SeshatValue, ...] = ()
    script: tuple[SeshatValue, ...] = ()
    non_phonetic_writing: tuple[SeshatValue, ...] = ()
    phonetic_alphabetic_writing: tuple[SeshatValue, ...] = ()
    lists_tables_and_classifications: tuple[SeshatValue, ...] = ()
    calendar: tuple[SeshatValue, ...] = ()
    sacred_texts: tuple[SeshatValue, ...] = ()
    religious_literature: tuple[SeshatValue, ...] = ()
    practical_literature: tuple[SeshatValue, ...] = ()
    history: tuple[SeshatValue, ...] = ()
    philosophy: tuple[SeshatValue, ...] = ()
    fiction: tuple[SeshatValue, ...] = ()
    articles: tuple[SeshatValue, ...] = ()
    tokens: tuple[SeshatValue, ...] = ()
    foreign_coins: tuple[SeshatValue, ...] = ()
    indigenous_coins: tuple[SeshatValue, ...] = ()
    paper_currency: tuple[SeshatValue, ...] = ()
    couriers: tuple[SeshatValue, ...] = ()
    postal_stations: tuple[SeshatValue, ...] = ()
    general_postal_service: tuple[SeshatValue, ...] = ()
    scientific_literature: tuple[SeshatValue, ...] = ()
    precious_metals: tuple[SeshatValue, ...] = ()
    mnemonic_devices: tuple[SeshatValue, ...] = ()
    copper: tuple[SeshatValue, ...] = ()
    bronze: tuple[SeshatValue, ...] = ()
    iron: tuple[SeshatValue, ...] = ()
    steel: tuple[SeshatValue, ...] = ()
    javelins: tuple[SeshatValue, ...] = ()
    atlatl: tuple[SeshatValue, ...] = ()
    slings: tuple[SeshatValue, ...] = ()
    self_bow: tuple[SeshatValue, ...] = ()
    composite_bow: tuple[SeshatValue, ...] = ()
    crossbow: tuple[SeshatValue, ...] = ()
    tension_siege_engines: tuple[SeshatValue, ...] = ()
    sling_siege_engines: tuple[SeshatValue, ...] = ()
    gunpowder_siege_artillery: tuple[SeshatValue, ...] = ()
    handheld_firearms: tuple[SeshatValue, ...] = ()
    war_clubs: tuple[SeshatValue, ...] = ()
    battle_axes: tuple[SeshatValue, ...] = ()
    daggers: tuple[SeshatValue, ...] = ()
    swords: tuple[SeshatValue, ...] = ()
    spears: tuple[SeshatValue, ...] = ()
    polearms: tuple[SeshatValue, ...] = ()
    dogs: tuple[SeshatValue, ...] = ()
    donkeys: tuple[SeshatValue, ...] = ()
    horses: tuple[SeshatValue, ...] = ()
    camels: tuple[SeshatValue, ...] = ()
    wood_bark_etc: tuple[SeshatValue, ...] = ()
    leather_cloth: tuple[SeshatValue, ...] = ()
    shields: tuple[SeshatValue, ...] = ()
    helmets: tuple[SeshatValue, ...] = ()
    breastplates: tuple[SeshatValue, ...] = ()
    limb_protection: tuple[SeshatValue, ...] = ()
    scaled_armor: tuple[SeshatValue, ...] = ()
    laminar_armor: tuple[SeshatValue, ...] = ()
    plate_armor: tuple[SeshatValue, ...] = ()
    small_vessels_canoes_etc: tuple[SeshatValue, ...] = ()
    merchant_ships_pressed_into_service: tuple[SeshatValue, ...] = ()
    specialized_military_vessels: tuple[SeshatValue, ...] = ()
    settlements_in_a_defensive_position: tuple[SeshatValue, ...] = ()
    wooden_palisades: tuple[SeshatValue, ...] = ()
    earth_ramparts: tuple[SeshatValue, ...] = ()
    ditch: tuple[SeshatValue, ...] = ()
    moat: tuple[SeshatValue, ...] = ()
    stone_walls_non_mortared: tuple[SeshatValue, ...] = ()
    stone_walls_mortared: tuple[SeshatValue, ...] = ()
    fortified_camps: tuple[SeshatValue, ...] = ()
    complex_fortifications: tuple[SeshatValue, ...] = ()
    long_walls: tuple[SeshatValue, ...] = ()
    modern_fortifications: tuple[SeshatValue, ...] = ()
    elephants: tuple[SeshatValue, ...] = ()
    chainmail: tuple[SeshatValue, ...] = ()
    elite_status_is_hereditary: tuple[SeshatValue, ...] = ()
    rulers_are_legitimated_by_gods: tuple[SeshatValue, ...] = ()
    rulers_are_gods: tuple[SeshatValue, ...] = ()
    ideological_reinforcement_of_equality: tuple[SeshatValue, ...] = ()
    ideological_thought_equates_rulers_and_commoners: tuple[SeshatValue, ...] = ()
    ideological_thought_equates_elites_and_commoners: tuple[SeshatValue, ...] = ()
    ideology_reinforces_prosociality: tuple[SeshatValue, ...] = ()
    production_of_public_goods: tuple[SeshatValue, ...] = ()
    moral_concern_is_primary: tuple[SeshatValue, ...] = ()
    moralizing_enforcement_is_certain: tuple[SeshatValue, ...] = ()
    moralizing_norms_are_broad: tuple[SeshatValue, ...] = ()
    moralizing_enforcement_is_targeted: tuple[SeshatValue, ...] = ()
    moralizing_enforcement_of_rulers: tuple[SeshatValue, ...] = ()
    moralizing_religion_adopted_by_elites: tuple[SeshatValue, ...] = ()
    moralizing_religion_adopted_by_commoners: tuple[SeshatValue, ...] = ()
    moralizing_enforcement_in_afterlife: tuple[SeshatValue, ...] = ()
    moralizing_enforcement_in_this_life: tuple[SeshatValue, ...] = ()
    moralizing_enforcement_is_agentic: tuple[SeshatValue, ...] = ()
    constraint_on_executive_by_government: tuple[SeshatValue, ...] = ()
    constraint_on_executive_by_non_government: tuple[SeshatValue, ...] = ()
    impeachment: tuple[SeshatValue, ...] = ()


class AIAnswer(BaseModel):
    model_name: str | None = Field(None, description="The language model that produced the value.")
    prompt_id: str | None = Field(None, description="The prompt it was given.")


class Provenance(BaseModel):
    raw: tuple[str, ...] = Field((), description="The fields of datamodel_raw.py this value was built from, as 'Model.field' — 'IndividualWikidata.date_of_birth', 'CrossVerifiedPerson.birth', 'PolityCliopatria.geometry'. Every source the project reads is in that file in full, so this is the link back to the data exactly as it arrived, and from there to a Wikidata property and its definition.")
    inputs: tuple[str, ...] = Field((), description="For a value computed from another computed one, the fields of this table it was built on — the floruit from its start and end. Values read from a source name those in `raw` instead.")
    rule: str | None = Field(None, description="For a computed value, what was done to those inputs, in one sentence. This is the whole method: there is no step recorded elsewhere.")
    ai_answer: AIAnswer | None = Field(None, description="Set when a language model produced the value rather than a rule — which model, and which prompt it was given. A value with this is a judgement, not a lookup, and is the one kind here that a rerun can change.")
    retrieved_on: date | None = Field(None, description="The day the source was read. Wikidata is edited continuously, so a value without this cannot be reproduced.")


class WikidataEntity(BaseModel):
    qid: str | None = Field(None, description="The Wikidata item, 'Q1339'.")
    label_en: str | None = Field(None, description="Its English label.")
    description: str | None = Field(None, description="Its English description.")


class Date(BaseModel):
    iso: str | None = Field(None, description="The date as the source states it, ISO 8601, negative before the common era.")
    year: int | None = Field(None, description="Its year.")
    precision: str | None = Field(None, description="How finely the source states it — 'day', 'year', 'decade', 'century'.")
    field_provenance: dict[str, Provenance] = Field({}, description="Which source this one date came from. It is here and not on the individual because the dates of one column can come from different sources.")


class CliopatriaPolity(BaseModel):
    cliopatria_id: int | None = Field(None, description="Cliopatria's identifier for the polity — assigned by this project when the GeoJSON was loaded, since Cliopatria itself numbers nothing.")
    name: str | None = Field(None, description="The polity's name as Cliopatria spells it — 'Ottoman Empire', 'Magadha - Shaishunaga dynasty'. Its own spelling, not Wikidata's.")
    entity: WikidataEntity | None = Field(None, description="The Wikidata item Cliopatria resolved for the polity, where it resolved one — the join out to Wikidata and to the other tables here. Empty for a polity it could not resolve, which is why cliopatria_id and not a qid is this table's key.")
    field_provenance: dict[str, Provenance] = Field({}, description="How each value on this row came to be, keyed by column — the raw field it was read from, or the rule that produced it.")


class Individual(BaseModel):
    wikidata_id: str = Field(..., description="The individual's Wikidata qid, Cultura's Individual.entity.qid. The key.")
    label_en: str | None = Field(None, description="Its English label, to read a row without a lookup.")
    birth_date: tuple[Date, ...] = Field((), description="Cultura's Individual.birth_date: one date per source, copied as is.")
    death_date: tuple[Date, ...] = Field((), description="Cultura's Individual.death_date: one date per source, copied as is.")
    occupation: tuple[WikidataEntity, ...] = Field((), description="Cultura's Individual.occupation, the Wikidata P106 items, without their subclass_of — that hierarchy is on Cultura's occupation table.")
    number_of_works: int = Field(0, description="How many distinct works Cultura credits the individual with — the distinct work_qid of Individual.work, whatever the credit property (P50 author, P170 creator, P86 composer…). 0 for someone credited with none.")
    is_artist: bool | None = Field(None, description="Cultura's Individual.is_artist.")
    is_scientist: bool | None = Field(None, description="Cultura's Individual.is_scientist.")
    cliopatria_polity: CliopatriaPolity | None = Field(None, description="The main Cliopatria polity Cultura assigned the individual to — a sub-polity before a meta polity, then the most years_spent_in_polity, then Cultura's order — as Cultura's polity table has it, without its territories: their polygons and borders stay in Cultura.")
    seshat_polity: tuple[SeshatPolity, ...] = Field((), description="The Seshat polities the individual is linked to: the seshat_ids Cultura gives the assignment to cliopatria_polity — the ids of that polity's territories overlapping the individual's peak activity window — split on ';', as entries of Seshat's polity list, ordered by id. Several when the window spans a change of Seshat polity.")
    field_provenance: dict[str, Provenance] = Field({}, description="Where each value came from, keyed by field name. Every entry names the raw fields behind the column, and for all but the two date columns it carries no rule: the values here are the raw ones unquoted and stripped of their stamps, nothing more, and any change of shape — a qid resolved to a label — is on IndividualEnriched. The entries for birth_date and death_date are the exception, and they are here only to say that the column is a list of one date per source; which source any one of those dates came from is on that date's own field_provenance and nowhere else, because a column-level entry repeated on every row cannot tell a P569 date from a year read out of a description. The entries copied from Cultura are its own; number_of_works, cliopatria_polity and seshat_polity, which this project builds, carry the rule that built them. A Cultura column with no entry on a row — is_artist and is_scientist, left unset where Cultura did not decide — has none here either.")


class UnseenSpecies(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    home_seshat_region: str = Field(..., description="SeshatPolity.home_seshat_region of the individuals' Seshat polities, 'North China'. With century it is the key.")
    century: int = Field(..., description="The century of the individuals' year — death year, else birth year — floored: 1600 holds 1600 to 1699. From -500 to 1700: the data stop before 1800, so every century is complete.")
    f0: float = Field(..., description="The unseen individuals of the generalized Chao model: the sum, over the century's singletons and doubletons, of 1 / (l + l² / 2), l = 2p / (1 - p), p the probability of being a doubleton given by a logistic regression on a spline of the decade, the occupation group and the home region.")
    f0_min: float = Field(..., description="f0 at the upper bound of the 95% confidence interval of p.")
    f0_max: float = Field(..., description="f0 at the lower bound of the 95% confidence interval of p.")
    f1: int = Field(..., description="Individuals with 0 or 1 work: singletons, an individual with no recorded work counting as one.")
    f2: int = Field(..., description="Individuals with 2 works: doubletons.")
    f_more_than_2: int = Field(..., alias="f>2", description="Individuals with more than 2 works. Not in the model, which fits singletons and doubletons only.")
